package com.umc.EveryWear.domain.product.exception.code;

import com.umc.EveryWear.global.apiPayload.code.BaseSuccessCode;
import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ProductSuccessCode implements BaseSuccessCode {

    MUSINSA_PRODUCT_ADDED(HttpStatus.OK,
            "PRODUCT201",
            "무신사 상품을 신규 추가했습니다."),
    MUSINSA_PRODUCT_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "무신사 상품을 등록했습니다."),
    MUSINSA_PRODUCT_URL_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "무신사 상품의 URL을 업데이트했습니다."),
    ZIGZAG_PRODUCT_ADDED(HttpStatus.OK,
            "PRODUCT201",
            "지그재그 상품을 신규 추가했습니다."),
    ZIGZAG_PRODUCT_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "지그재그 상품을 등록했습니다."),
    ZIGZAG_PRODUCT_URL_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "지그재그 상품의 URL을 업데이트했습니다."),
    WCONCEPT_PRODUCT_ADDED(HttpStatus.OK,
            "PRODUCT201",
            "W컨셉 상품을 신규 추가했습니다."),
    WCONCEPT_PRODUCT_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "W컨셉 상품을 등록했습니다."),
    WCONCEPT_PRODUCT_URL_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "W컨셉 상품의 URL을 업데이트했습니다."),
    CM29_PRODUCT_ADDED(HttpStatus.OK,
            "PRODUCT201",
            "29cm 상품을 신규 추가했습니다."),
    CM29_PRODUCT_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "29cm 상품을 등록했습니다."),
    CM29_PRODUCT_URL_UPDATED(HttpStatus.OK,
            "PRODUCT202",
            "29cm 상품의 URL을 업데이트했습니다."),
    PRODUCTS_RETRIEVED(HttpStatus.OK,
            "PRODUCT200",
            "전체 상품을 조회했습니다."),
    TOP_PRODUCTS_RETRIEVED(HttpStatus.OK,
            "PRODUCT210",
            "상의 상품을 조회했습니다."),
    BOTTOM_PRODUCTS_RETRIEVED(HttpStatus.OK,
            "PRODUCT211",
            "하의 상품을 조회했습니다."),
    OUTER_PRODUCTS_RETRIEVED(HttpStatus.OK,
            "PRODUCT212",
            "아우터 상품을 조회했습니다."),
    DRESS_PRODUCTS_RETRIEVED(HttpStatus.OK,
            "PRODUCT213",
            "원피스 상품을 조회했습니다."),
    ETC_PRODUCTS_RETRIEVED(HttpStatus.OK,
            "PRODUCT214",
            "기타 상품을 조회했습니다."),
    PRODUCTS_RETRIEVED_EMPTY(HttpStatus.OK,
            "PRODUCT204",
            "상품을 조회했습니다. 응답 본문이 없습니다."),
    PRODUCT_LIKE_ENABLED(HttpStatus.OK,
            "PRODUCT220",
            "상품 좋아요가 성공적으로 활성화되었습니다."),
    PRODUCT_LIKE_DISABLED(HttpStatus.OK,
            "PRODUCT221",
            "상품 좋아요가 성공적으로 비활성화되었습니다."),
    PRODUCT_FITTING_200(HttpStatus.OK,
            "PRODUCT230",
            "단건 상품을 조회했습니다."),
    PRODUCT_CRAWL_STARTED(HttpStatus.OK,
            "PRODUCT240",
            "상품 등록 백그라운드 작업이 시작되었습니다. 상태 조회 API로 완료 여부를 확인해 주세요."),
    PRODUCT_CRAWL_COMPLETED(HttpStatus.OK,
            "PRODUCT241",
            "상품 등록이 완료되었습니다."),
    PRODUCT_CRAWL_FAILED(HttpStatus.OK,
            "PRODUCT242",
            "상품 정보 모으기에 실패했습니다."),
    ;

    private final HttpStatus status;
    private final String code;
    private final String message;
}
